### ISSUE TITLE
tag20230504193158的 WARP模式下报错404

### ISSUE THREAD

**Issue by huangwb8** [linweiyuan/go-chatgpt-api#103]
使用latest(`linweiyuan/go-chatgpt-api:20230504193158`)时，WARP模式下聊天会出现404报错：

```
ChatGPT error 404: 404 page not found
```

使用`linweiyuan/go-chatgpt-api:20230504095144`正常。

代码是：

```yaml

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    # image: linweiyuan/go-chatgpt-api:latest
    image: linweiyuan/go-chatgpt-api:20230504095144
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
```

大家有这种情况吗？
