### ISSUE TITLE
发一个现在能用的Docker compose配置 浏览器模拟All in one 

### ISSUE THREAD

**Issue by tanpengsccd** [linweiyuan/go-chatgpt-api#124]
```yml
version: "3"

services:
  
  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
    
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image:  linweiyuan/go-chatgpt-api:legacy  #linweiyuan/go-chatgpt-api:latest #linweiyuan/go-chatgpt-api 
    # ports:
    #   - 33132:8080
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
  chatgpt-share:
    container_name: chatgpt-share
    image: ghcr.io/moeakwak/chatgpt-web-share:latest
    restart: always
    ports:
      - 12080:80 # web 端口号
    #   - 12800:8000 # 后端
    volumes:
      - ./data:/data # 存放数据库文件以及统计数据
      - ./config.yaml:/app/backend/api/config/config.yaml # 后端配置文件
      - ./logs:/app/logs # 存放日志文件
      # - ./dist:/app/dist
    environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/ #chatgpt/
    depends_on:
      - go-chatgpt-api
    labels: 
    # 设置Host 为 进行域名访问,改为自己的
      - "traefik.http.routers.chatgpt_web_share.rule=Host(`ai.yourdomain.com`)"
      - traefik.http.services.chatgpt_web_share.loadbalancer.server.port=80
      - traefik.http.routers.chatgpt_web_share.tls=true
      - traefik.http.routers.chatgpt_web_share.tls.certresolver=le
# 使用已存在的 traefik 的 network
networks:
 default:
   name: docker_manage_default
   external: true

```
http 端口开在 12080  , label 的内容可以 注释,那是给 traefik 用的.

config.yml 据自己实际情况修改. 就不贴了.
