### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by itcuihao** [linweiyuan/go-chatgpt-api#129]
docker-compose.yaml
```
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 6060:8080
    environment:
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=OFF
    restart: unless-stopped
```

```
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2023/05/17 - 05:43:51 | 404 |       3.284µs |      172.28.0.1 | GET      "/chatgpt/conversation/034f5d24-1ecf-452e-a735-2f39424257ee"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0x7b0566]

goroutine 6 [running]:
github.com/linweiyuan/go-chatgpt-api/api/chatgpt.tryToRefreshPage()
	/app/api/chatgpt/chatgpt.go:47 +0x26
github.com/linweiyuan/go-chatgpt-api/api/chatgpt.init.0.func1()
	/app/api/chatgpt/chatgpt.go:39 +0x3c
created by github.com/linweiyuan/go-chatgpt-api/api/chatgpt.init.0
	/app/api/chatgpt/chatgpt.go:34 +0x25
```

**Comment by linweiyuan** [comment]
你这个镜像 N 年前的了，更新下

**Comment by itcuihao** [comment]
> 你这个镜像 N 年前的了，更新下

好吧，我从`readme_zh.md` 抄过来的

**Comment by itcuihao** [comment]
> 你这个镜像 N 年前的了，更新下

更新后错误依旧，请问有没有最新配置的模板，麻烦举个栗子

**Comment by linweiyuan** [comment]
新版本 `chatgpt.go` 这个文件都不在了，错误依旧可能是没更新到

怎样更新的？

目前 `go-chatgpt-api` 最新镜像 ID：`c66677f03a73`

**Comment by linweiyuan** [comment]
`docker-compose pull`

**Comment by itcuihao** [comment]
> 新版本 `chatgpt.go` 这个文件都不在了，错误依旧可能是没更新到
> 
> 怎样更新的？
> 
> 目前 `go-chatgpt-api` 最新镜像 ID：`c66677f03a73`

我的文件，麻烦帮忙review了

```
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api:latest
    ports:
      - 6060:8080
    environment:
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp:latest
    environment:
      - LOG_LEVEL=OFF
    restart: unless-stopped
```
