### ISSUE TITLE
Failed to get cookies, please try again later

### ISSUE THREAD

**Issue by Gavenvincent** [linweiyuan/go-chatgpt-api#130]
晚上看到chatgpt-proxy-server-warp有更新，所以删除了以前安装的，然后重新拉取最新的镜像，非chrome ，但启动后报Failed to get cookies, please try again later，然后没有welcome提示日志，这个怎么解决呢？以下是日志：
{"log":"\u001b[36mINFO\u001b[0m[0000] \u001b[1;32mGO_CHATGPT_API_PROXY: socks5://chatgpt-proxy-server-warp:65535\u001b[0m \n","stream":"stderr","time":"2023-05-17T12:21:51.058860408Z"}
{"log":"\u001b[31mERRO\u001b[0m[0002] \u001b[1;31mFailed to get cookies, please try again later.\u001b[0m \n","stream":"stderr","time":"2023-05-17T12:21:53.650442397Z"}
{"log":"[GIN] 2023/05/17 - 20:25:45 |\u001b[90;43m 403 \u001b[0m|  239.959593ms |      172.26.0.1 |\u001b[97;46m POST    \u001b[0m \"/chatgpt/conversation\"\n","stream":"stdout","time":"2023-05-17T12:25:45.132141897Z"}
{"log":"[GIN] 2023/05/17 - 20:28:04 |\u001b[90;43m 403 \u001b[0m|  235.790112ms |      172.26.0.1 |\u001b[97;46m POST    \u001b[0m \"/chatgpt/conversation\"\n","stream":"stdout","time":"2023-05-17T12:28:04.726693386Z"}

**Comment by linweiyuan** [comment]
看下是不是好了，看到日志，cookie api 两个小时前挂到现在

但是没人提我也不知道

**Comment by linweiyuan** [comment]
刚才顺便重启了下，现在呢

**Comment by Gavenvincent** [comment]
感谢大佬，好了 @linweiyuan

**Comment by dwdcth** [comment]
> 需要重启compose，我重启了下，现在好了，你重启一下试试 @dwdcth

好了，谢谢

**Comment by Gavenvincent** [comment]
感谢大佬

**Comment by HLiamso** [comment]
又挂了

**Comment by linweiyuan** [comment]
> 又挂了

恢复了

**Comment by HLiamso** [comment]
好奇问一问这个cookie的服务器可以自己搭么，另外咱们这个仓库有没有tg交流群呢

**Comment by HLiamso** [comment]
> > 又挂了
> 
> 恢复了

感谢

**Comment by linweiyuan** [comment]
> 好奇问一问这个cookie的服务器可以自己搭么，另外咱们这个仓库有没有tg交流群呢

我没有加任何群，不知道其他人有没有

如果自己搭建，那不如用 `legacy` 版本，这个 `cookie` 无非就是从浏览器那里获取回来

**Comment by CCiner** [comment]
```
$ sudo docker-compose up
Starting chatgpt-proxy-server-warp ... done
Starting go-chatgpt-api            ... done
Attaching to chatgpt-proxy-server-warp, go-chatgpt-api
go-chatgpt-api               | INFO[0000] GO_CHATGPT_API_PROXY: socks5://chatgpt-proxy-server-warp:65535
chatgpt-proxy-server-warp    | Success
chatgpt-proxy-server-warp    | Error: Old registration is still around. Try running: warp-cli delete
chatgpt-proxy-server-warp    | Success
chatgpt-proxy-server-warp    | Success
go-chatgpt-api               | ERRO[0002] Failed to get cookies, please try again later.
```
会不会又挂了  我使用的是docker-compose是抄的
```
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=OFF
    restart: unless-stopped
```
海外服务器
