### ISSUE TITLE
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

### ISSUE THREAD

**Issue by justincnn** [linweiyuan/go-chatgpt-api#131]
求助：

vps设置warp之后，搭梯子可以访问ai.com没有问题，

但是通过go-chatgpt-api，就提示：[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

用的是最新的docker

**Comment by justincnn** [comment]
> 国内 VPS？
> 
> 发下配置文件

具体如下，麻烦看下：

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    network_mode: "host"
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped
~

**Comment by justincnn** [comment]
> 国内 VPS？这个为什么不答
> 
> 这个配置不对，`network_mode` 是从哪里抄的
> 
> `GO_CHATGPT_API_PROXY` 留空也不对

国外的，用的是甲骨文的vps，ip断已经被chatgpt拦掉了，

换行问题是我刚才复制的格式有问题引起的，

格式具体如下，另外关于network_mode该如何修改，谢谢呀


services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    network_mode: "host"
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped

**Comment by linweiyuan** [comment]
`README` 文档里也有

```yaml
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=OFF
    restart: unless-stopped
```
