### ISSUE TITLE
本地部署问题，卡在INFO[0000] Service go-chatgpt-api is ready.

### ISSUE THREAD

**Issue by Himeno-Yumemi** [linweiyuan/go-chatgpt-api#155]
compose.yaml文件：
```
services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 9500:9500
    environment:
      - TZ=Asia/Shanghai
      #- GO_CHATGPT_API_PROXY=
    restart: unless-stopped
```
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/49085794/758e7c6e-cd0d-4c2a-bb57-35fafd9a5406)
openai是能正常连接的
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/49085794/b9b5e0d3-605e-4553-9dd6-58ad1a239f0f)
