### ISSUE TITLE
docker部署报错：ERRO[0000] Health check failed:

### ISSUE THREAD

**Issue by Joackk** [linweiyuan/go-chatgpt-api#251]
日志中内容如下图
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/45162558/f12f597f-bf0d-44b4-94e2-100a3cca36a7)
docker-compose.yml文件内容如下
version: "3"
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

网络状况正常，可以正常访问chatgpt。
请问大佬如果想要使用伪api，我该把账号密码写在环境变量里吗？

**Comment by linweiyuan** [comment]
第二个问题，不用

第一个问题，看上去网络不太正常，不要相信那个所谓的检测脚本

**Comment by Joackk** [comment]
> 第二个问题，不用
> 
> 第一个问题，看上去网络不太正常，不要相信那个所谓的检测脚本

大佬这样是成功了吗？我看没有报错了，但是无法访问到8080 
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/45162558/25e0fb00-b8ed-4b19-94d5-cdef7d28b77f)
然后尝试py中使用api
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/45162558/ce094bc5-13b1-4711-a21d-a54e8bc4dc20)

**Comment by linweiyuan** [comment]
不好意思忘了这件事了，能分享完成的 py 代码吗，不是很懂 py，看上去像是说 json 解析失败之类的

**Comment by Joackk** [comment]
> 不好意思忘了这件事了，能分享完成的 py 代码吗，不是很懂 py，看上去像是说 json 解析失败之类的

没事没事，大佬能回复就很感谢了。代码如下：
import openai

openai.api_key = ""
openai.api_base = "http://127.0.0.1:8080/v1"

while True:
    text = input("请输入问题：")
    response = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {'role': 'user', 'content': text},
        ],
        stream=True,
        allow_fallback=True
    )

    for chunk in response:
        print(chunk.choices[0].delta.get("content", ""), end="", flush=True)
    print("\n")

**Comment by Joackk** [comment]
> 不好意思忘了这件事了，能分享完成的 py 代码吗，不是很懂 py，看上去像是说 json 解析失败之类的

对了大佬，还有就是在虚拟桌宠（[VPet）里调用也是这样，我打包成api主要就是想给翻译器和一些其他软件用

**Comment by linweiyuan** [comment]
改为这个，亲测

`openai.api_base = "http://127.0.0.1:8080/imitate/v1"`

**Comment by Joackk** [comment]
> 改为这个，亲测
> 
> `openai.api_base = "http://127.0.0.1:8080/imitate/v1"`

soga，等我回去试一下，感谢大佬，大佬这不是把自己账号转换为api的吗？我一直很奇怪直接拉去docker都没写入我的账号，他转的那里的账号的哇

**Comment by linweiyuan** [comment]
token 里面有账号信息

**Comment by Joackk** [comment]
> token 里面有账号信息

是要设置token或者环境变量吗？我是只有一个docker-compose文件，啥都没了，文件内容就如下，我是要再加一个env文件之类的来存token吗？
```
version: "3"
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - PROXY=socks5://10.162.67.61:7890
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
    restart: unless-stopped
```
