### ISSUE TITLE
chatgpt-proxy-server-warp

### ISSUE THREAD

**Issue by zuozihan** [linweiyuan/go-chatgpt-api#27]
chatgpt-proxy-server-warp 这是什么问题，linux用的梯子，不是国外服务器
![image](https://user-images.githubusercontent.com/45542784/232440220-3c02c467-cf93-48c1-ba0f-054975769549.png)

**Comment by linweiyuan** [comment]
如果尝试跑其他那些配置 warp 的脚本，可以用吗？

这个看上去就是网连不上，但是具体的问题，不是很清楚

**Comment by zuozihan** [comment]
你好我warp跑起来了，好像也没报错，但是go-chatgpt-api还是提示 Access denied
![image](https://user-images.githubusercontent.com/45542784/232698125-7da742c5-5d55-4e40-bed6-0f8e45c98167.png)
![image](https://user-images.githubusercontent.com/45542784/232698165-5e0976fd-6c24-4eb5-9cbe-262256e88393.png)

**Comment by linweiyuan** [comment]
![2023-04-18_15-13](https://user-images.githubusercontent.com/49076004/232700227-c630d626-47d3-4ff1-acc0-d3113c60907f.png)

你这个 IP 显示所在地在广州，国内没权限，应该和这个有关

但是我也不知道怎么解决，可能要套多层代理

**Comment by zuozihan** [comment]
我将warp取消了，并且发送了一个请求，但是服务端没有响应
![image](https://user-images.githubusercontent.com/45542784/232707853-95a2a43c-d35e-4800-84ac-a27853ade109.png)

**Comment by linweiyuan** [comment]
`token` 打个码

**Comment by zuozihan** [comment]
> 看上去是没有问题的，出现了 `Welcome to ChatGPT` 就是能用了
> 
> 至于为什么没响应，试一下 `exec` 进去 `chatgpt-app` 这个容器，`ping go-chatgpt-api` 看通不通
> 
> 或者把 `yaml` 文件贴出来看看，删掉 `token`


可以ping通
![image](https://user-images.githubusercontent.com/45542784/232710696-ed06e3c0-6855-4348-ac2a-ff17057d9887.png)

```yml
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 0.0.0.0:3002:3002
    environment:
      # 二选一
      # OPENAI_API_KEY: sk-xxx
      # 二选一
      OPENAI_ACCESS_TOKEN: 
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      # OPENAI_API_BASE_URL: xxx
      # API模型，可选，设置 OPENAI_API_KEY 时可用，https://platform.openai.com/docs/models
      # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, code-davinci-002
      #  OPENAI_API_MODEL: xxx
      # 反向代理，可选
      API_REVERSE_PROXY: http://go-chatgpt-api:8080/conversation
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: 
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      # SOCKS_PROXY_HOST: xxx
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      # SOCKS_PROXY_PORT: xxx
      # HTTPS 代理，可选，支持 http，https，socks5
      # HTTPS_PROXY: http://xxx:7890
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
    #  - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      #- chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

  #chatgpt-proxy-server-warp:
   # container_name: chatgpt-proxy-server-warp
   # image: linweiyuan/chatgpt-proxy-server-warp
   # restart: unless-stopped
```

**Comment by linweiyuan** [comment]
看上去没什么问题，刚在本地试了这个配置也正常，或者你加个 `depends_on` 在 `app` 上试试

```yaml
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ...省略...
    depends_on:
      - go-chatgpt-api
```
