### ISSUE TITLE
提供错误的API密钥，使用的是accesstoken

### ISSUE THREAD

**Issue by joezjy** [linweiyuan/go-chatgpt-api#40]
使用accesstoken，没有用api，但回复提示这个错误：提供错误的API密钥

**Comment by joezjy** [comment]
前端是这个：**Chanzhaoyu/chatgpt-web**，其他的是**go-chatgpt-api** + **chatgpt-proxy-server** + **chatgpt-proxy-server-warp**


yaml是这些：
```yaml
version: '3'

services:
  app:
    container_name: chatgpt-forMe
    image: chenzhaoyu94/chatgpt-web
    restart: always
    ports:
      - 3002:3002
    environment:
      API_REVERSE_PROXY: "http://go-chatgpt-api:8080/conversation"
      OPENAI_ACCESS_TOKEN: "这里填了token"
      TIMEOUT_MS: 60000
```

```yaml
version: '3'

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080 # 宿主机8080端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped
 
  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
 
  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
```
