### ISSUE TITLE
频繁出现 [OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

### ISSUE THREAD

**Issue by huangwb8** [linweiyuan/go-chatgpt-api#93]
我很早就开始使用本项目了 (ฅ´ω`ฅ) 

昨天我看到本项目的更新，即不再需要`chatgpt-proxy-server`，所以我尝试了最新的方案。

我使用的`go-chatgpt-api`版本是：

```json
[
    {
        "Id": "952e6c260ebd9c6c812836b93cc96308c11be589800a85ba4ce9f29f377f52be",
        "Created": "2023-04-29T23:54:32.930107483Z",
        "Path": "/app/go-chatgpt-api",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 466863,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-04-29T23:54:34.372380033Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:52df78ab127aafeccae0c2d8ae2d2415cf9e4e752258385f3c93888480f109fc",
        ...
    }
]
```

但是，我发现它会频繁出现报错： `[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later`。刷新一下可以正常输出。这和以前我们直接访问网页时非常相似。 我感觉没有之前使用chatgpt-proxy-server的时候稳定。

不知大家有没有这种情况？

**Comment by Beckjiang** [comment]
我遇到同样的问题403，使用了warp也一样。机器在东京

**Comment by huangwb8** [comment]
@Beckjiang 

是啊，作者昨天一波更新，以为已经稳定了，大意了！

![PwBrHcGx84](https://user-images.githubusercontent.com/35643122/235329987-dcc9a927-235f-4022-80eb-821b415c58e4.png)

希望大佬 @linweiyuan 可以出一个稳定的旧版本镜像，使用旧的方案，让咱们过渡一下。 旧的方案很稳 (ฅ´ω`ฅ)

现在只有latest，不知道怎么下载旧的镜像

**Comment by linweiyuan** [comment]
刷新一下是重启 API 吗？

**Comment by huangwb8** [comment]
> 刷新一下是重启 API 吗？

我是这样做的。 之前的版本的docker-compose.yml内容是：

```yaml
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080 # 宿主机8080端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
```
昨天，我用docker-compose pull更新镜像后，用的是新的方案：

```yaml
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
```
这个新的方案是非常不稳定的，经常出现`[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later`。

**Comment by huangwb8** [comment]
> 刷新一下是重启 API 吗？

其实不太懂大佬您要问什么。 我使用的并不是API模式，而是Access Token的模式。 API模式我不需要用这个反向代理。

**Comment by nephen** [comment]
我的报403
```
[GIN] 2023/04/30 - 07:52:01 | 403 |  1.762843867s |             ::1 | GET      "/conversations?limit=5&offset=0"
```

**Comment by huangwb8** [comment]
我请小伙伴build了一个旧版本的go-chatgpt-api，供大家过渡使用：

```bash
docker pull ddsderek/go-chatgpt-api:latest
```

使用旧的方法和参数：

```yaml
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: ddsderek/go-chatgpt-api
    ports:
      - 8080:8080 # 宿主机8080端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
```

希望大佬们能尽快修复这个bug ヾ(≧∇≦*)ゝ 加油
