### ISSUE TITLE
Watchtower更新go-chatgpt-api异常

### ISSUE THREAD

**Issue by huangwb8** [linweiyuan/go-chatgpt-api#99]
我的Watchtower的Docker Compose是这样的：

```yaml

version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      WATCHTOWER_NOTIFICATION_TITLE_TAG: Test
      WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: hwb2012@qq.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: xxxxxxxx@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.qq.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 465
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: hwb2012@qq.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: xxxxxxxx
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: rsshub:chromium-bundled watchtower go-chatgpt-api chatgpt-proxy-server-warp duplicat portainer privatebin vaultwarden/server wallabag wangqiru/ttrss alist --cleanup --interval 3600 
```

但是，我发现它更新了镜像，却没有应用该镜像：

![image](https://user-images.githubusercontent.com/35643122/236184845-e98eff63-9eb6-4b94-8f46-3c5e0b2547ae.png)

但我其它的镜像更新是正常的。 请问有小伙伴有类似的情况吗？
